USEMODULE += msp430_common
USEMODULE += msp430_common_periph
USEMODULE += periph

FEATURES_REQUIRED_ANY += newlib|picolibc
ifneq (,$(filter newlib,$(USEMODULE)))
  # use the nano-specs of Newlib when available
  DEFAULT_MODULE += newlib_nano
endif

# Make calls to malloc and friends thread-safe
USEMODULE += malloc_thread_safe
