MODULE := gnrc_sixlowpan_frag_sfr

SRC := $(MODULE).c

# enable submodules
SUBMODULES := 1

# this module is expected to pass static analysis
MODULE_SUPPORTS_STATIC_ANALYSIS := 1

include $(RIOTBASE)/Makefile.base
